#!/usr/bin/env php
<?php

include "vendor/autoload.php";
use Symfony\Component\Console\Application;
use Simplified\Console\Migrate;
use Simplified\Console\MigrateMake;

$app = new Application("Simplified");
$app->add(new Migrate());
$app->add(new MigrateMake());
$app->run();